== Autores
Bruno Cabrita nº57833 bm.cabrita@campus.fct.unl.pt +
Diogo Fona nº57940 d.fona@campus.fct.unl.pt +
Diogo Almeida nº58369 daro.almeida@campus.fct.unl.pt +

== DEPLOY
Azure::
URL: https://scc-backend-57833-57940-58369.azurewebsites.net/
[source,shell]
----
mvn compile package azure-webapp:deploy
----

Docker::
URL: http://localhost:8080/

.launch container (run just once)
[source,shell]
----
docker run -it --rm --network host -v "$(pwd)/modules/backend-app/target/scc-backend-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war" --env-file azure.env tomcat:latest
----

.package
[source,shell]
----
mvn compile package
----

Podman::
URL: http://localhost:8080/

.launch container (run just once)
[source,shell]
----
podman run -it --rm --network host -v ./modules/backend-app/target/scc-backend-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war:Z --env-file azure.env docker.io/tomcat:latest
----

.package
[source,shell]
----
mvn compile package
----

.Template azure.env file
[source,shell]
----
BACKEND_KIND=
AZURE_BLOB_STORAGE_CONNECTION_STRING=
AZURE_BLOB_STORAGE_AUCTION_MEDIA_CONTAINER_NAME=
AZURE_BLOB_STORAGE_USER_MEDIA_CONTAINER_NAME=
AZURE_COSMOS_DB_KEY=
AZURE_COSMOS_DB_URL=
AZURE_COSMOS_DB_DATABASE=
AZURE_COSMOS_DB_USER_CONTAINER_NAME=
AZURE_COSMOS_DB_AUCTION_CONTAINER_NAME=
AZURE_COSMOS_DB_BID_CONTAINER_NAME=
AZURE_COSMOS_DB_QUESTION_CONTAINER_NAME=
AZURE_ENABLE_CACHING=
AZURE_REDIS_KEY=
AZURE_REDIS_URL=
----

== ENVIRONMENT VARIABLES

[cols="1,2"]
|===
|*Variable* 
|*Description*

| `BACKEND_KIND`
| The kind of backend to use. Can be `azure`.

| `AZURE_BLOB_STORAGE_CONNECTION_STRING`
| The connection string to the Azure Blob Storage account.

| `AZURE_BLOB_STORAGE_AUCTION_MEDIA_CONTAINER_NAME`
| The name of the container to store auction media files.

| `AZURE_BLOB_STORAGE_USER_MEDIA_CONTAINER_NAME`
| The name of the container to store user media files.

| `AZURE_COSMOS_DB_KEY`
| The key to the Azure Cosmos DB account.

| `AZURE_COSMOS_DB_URL`
| The URL to the Azure Cosmos DB account.

| `AZURE_COSMOS_DB_DATABASE`
| The name of the database to use in the Azure Cosmos DB account.

| `AZURE_COSMOS_DB_USER_CONTAINER_NAME`
| The name of the container to store user documents.

| `AZURE_COSMOS_DB_AUCTION_CONTAINER_NAME`
| The name of the container to store auction documents.

| `AZURE_COSMOS_DB_BID_CONTAINER_NAME`
| The name of the container to store bid documents.

| `AZURE_COSMOS_DB_QUESTION_CONTAINER_NAME`
| The name of the container to store question documents.

| `AZURE_ENABLE_CACHING`
| Whether to enable caching. Can be `1` or `0`. Defaults to `0`.

| `AZURE_REDIS_KEY`
| The key to the Azure Redis Cache account.

| `AZURE_REDIS_URL`
| The URL to the Azure Redis Cache account.

| `AZURE_COGNITIVE_SEARCH_KEY`
| The key to the Azure Cognitive Search account.

| `AZURE_COGNITIVE_SEARCH_URL`
| The URL to the Azure Cognitive Search account.

| `AZURE_COGNITIVE_SEARCH_AUCTIONS_INDEX`
| The name of the auctions index in the Azure Cognitive Search account.

| `AZURE_COGNITIVE_SEARCH_QUESTIONS_INDEX`
| The name of the questions index in the Azure Cognitive Search account.

|===

== Creating a new Azure Function

=== Automatic

[source,shell]
----
$ scripts/function-create.py <function-name>
----

=== Manual

Change directory to `modules`.
[source,bash]
----
$ cd modules
----

Create a new maven module.
Use the name convention `function-<name>`.
[source,bash]
----
$ mvn -B archetype:generate \
    -DarchetypeGroupId=com.microsoft.azure \
    -DarchetypeArtifactId=azure-functions-archetype \
    -DjavaVersion=17 \
    -DgroupId=scc.azure.functions \
    -DappName='${project.artifactId}' \
    -DresourceGroup="scc2223-rg-westeurope-bdd" \
    -DappRegion="westeurope" \
    -DartifactId=scc-backend-azure-function-my-function-name
----

Modify the `pom.xml` in the new module.
Add the following properties:
[source,xml]
----
<properties>
    <functionPricingTier>B1</functionPricingTier>
</properties>
----

Add the folowing dependcy if the backend code is required:
[source,xml]
----
<dependencies>
    <dependency>
      <groupId>scc</groupId>
      <artifactId>scc-backend</artifactId>
      <version>${project.version}</version>
    </dependency>
</dependencies>
----

Add the new function to the root pom.xml.
[source,xml]
----
<modules>
    <module>modules/function-my-function-name</module>
</modules>
----

Deploy the function.
[source,bash]
----
$ cd modules/scc-backend-my-function-name
$ mvn compile package
$ mvn azure-functions:deploy
----

The function should now be available at `https://scc-backend-my-function-name.azurewebsites.net/api/`.