== Autores
Bruno Cabrita nº57833 bm.cabrita@campus.fct.unl.pt +
Diogo Fona nº57940 d.fona@campus.fct.unl.pt +
Diogo Almeida nº58369 daro.almeida@campus.fct.unl.pt +

== DEPLOY
Azure::
URL: https://scc-backend-57833-57940-58369.azurewebsites.net/
[source,shell]
----
mvn compile package azure-webapp:deploy
----

Docker::
URL: http://localhost:8080/

.launch container (run just once)
[source,shell]
----
docker run -it --rm --network host -v "$(pwd)/target/scc2223-lab1-1.0.war:/usr/local/tomcat/webapps/ROOT.war" --env-file azure.env tomcat:latest
----

.package
[source,shell]
----
mvn compile package
----

Podman::
URL: http://localhost:8080/

.launch container (run just once)
[source,shell]
----
podman run -it --rm --network host -v ./target/scc2223-lab1-1.0.war:/usr/local/tomcat/webapps/ROOT.war:Z --env-file azure.env docker.io/tomcat:latest
----

.package
[source,shell]
----
mvn compile package
----

.Template azure.env file
[source,shell]
----
BACKEND_KIND=
AZURE_BLOB_STORAGE_CONNECTION_STRING=
AZURE_BLOB_STORAGE_AUCTION_MEDIA_CONTAINER_NAME=
AZURE_BLOB_STORAGE_USER_MEDIA_CONTAINER_NAME=
AZURE_COSMOS_DB_KEY=
AZURE_COSMOS_DB_URL=
AZURE_COSMOS_DB_DATABASE=
AZURE_COSMOS_DB_USER_CONTAINER_NAME=
AZURE_COSMOS_DB_AUCTION_CONTAINER_NAME=
AZURE_COSMOS_DB_BID_CONTAINER_NAME=
AZURE_COSMOS_DB_QUESTION_CONTAINER_NAME=
AZURE_ENABLE_CACHING=
AZURE_REDIS_KEY=
AZURE_REDIS_URL=
----

== ENVIRONMENT VARIABLES

[cols="1,2"]
|===
|*Variable* 
|*Description*

| `BACKEND_KIND`
| The kind of backend to use. Can be `azure` or `memory`. Defaults to `memory`. Variables prefixed with `AZURE_` are only used if `BACKEND_KIND` is `azure`.

| `AZURE_BLOB_STORAGE_CONNECTION_STRING`
| The connection string to the Azure Blob Storage account.

| `AZURE_BLOB_STORAGE_AUCTION_MEDIA_CONTAINER_NAME`
| The name of the container to store auction media files.

| `AZURE_BLOB_STORAGE_USER_MEDIA_CONTAINER_NAME`
| The name of the container to store user media files.

| `AZURE_COSMOS_DB_KEY`
| The key to the Azure Cosmos DB account.

| `AZURE_COSMOS_DB_URL`
| The URL to the Azure Cosmos DB account.

| `AZURE_COSMOS_DB_DATABASE`
| The name of the database to use in the Azure Cosmos DB account.

| `AZURE_COSMOS_DB_USER_CONTAINER_NAME`
| The name of the container to store user documents.

| `AZURE_COSMOS_DB_AUCTION_CONTAINER_NAME`
| The name of the container to store auction documents.

| `AZURE_COSMOS_DB_BID_CONTAINER_NAME`
| The name of the container to store bid documents.

| `AZURE_COSMOS_DB_QUESTION_CONTAINER_NAME`
| The name of the container to store question documents.

| `AZURE_ENABLE_CACHING`
| Whether to enable caching. Can be `1` or `0`. Defaults to `0`.

| `AZURE_REDIS_KEY`
| The key to the Azure Redis Cache account.

| `AZURE_REDIS_URL`
| The URL to the Azure Redis Cache account.
|===
