package scc;

public enum ServiceError {
    BAD_REQUEST,
    UNAUTHORIZED,
    INVALID_CREDENTIALS,

    MEDIA_NOT_FOUND,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,

    AUCTION_NOT_FOUND,
    AUCTION_NOT_OPEN,
    BID_NOT_FOUND,
    BID_CONFLICT,
    QUESTION_NOT_FOUND,
    QUESTION_ALREADY_REPLIED,

    INTERNAL_ERROR,
}
