---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-backend-mongodb
spec:
  selector:
    matchLabels:
      app: scc-backend-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scc-backend-mongodb
    spec:
      containers:
        - name: scc-backend-mongodb
          image: docker.io/mongo:5.0.14
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-mongodb
spec:
  selector:
    app: scc-backend-mongodb
  ports:
    - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-mongodb-ld
spec:
  type: LoadBalancer
  selector:
    app: scc-backend-mongodb
  ports:
    - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-backend-redis
spec:
  selector:
    matchLabels:
      app: scc-backend-redis
  template:
    metadata:
      labels:
        app: scc-backend-redis
    spec:
      containers:
        - name: scc-backend-redis
          image: docker.io/redis:7.0.5
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-redis
spec:
  selector:
    app: scc-backend-redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-redis-lb
spec:
  type: LoadBalancer
  selector:
    app: scc-backend-redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scc-rabbitmq-cmap
data:
  config: ""
  plugins: |
    [rabbitmq_management,rabbitmq_management_agent].
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scc-rabbitmq-cmap-env
data:
  RABBITMQ_ENABLED_PLUGINS_FILE: /usr/local/configs/enabled_plugins
  #RABBITMQ_CONFIG_FILE: /usr/local/configs/rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-rabbitmq
spec:
  selector:
    matchLabels:
      app: scc-rabbitmq
  template:
    metadata:
      labels:
        app: scc-rabbitmq
    spec:
      containers:
        - name: scc-rabbitmq
          image: rabbitmq
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /usr/local/configs
              name: scc-rabbitmq-config-vol
          envFrom:
            - configMapRef:
                name: scc-rabbitmq-cmap-env
      volumes:
        - name: scc-rabbitmq-config-vol
          configMap:
            name: scc-rabbitmq-cmap
            items:
              - key: config
                path: rabbitmq.config
              - key: plugins
                path: enabled_plugins
---
apiVersion: v1
kind: Service
metadata:
  name: scc-rabbitmq
spec:
  selector:
    app: scc-rabbitmq
  ports:
    - port: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: scc-rabbitmq-lb
spec:
  selector:
    app: scc-rabbitmq
  type: LoadBalancer
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq
    - port: 15672
      targetPort: 15672
      name: rabbitmq-management
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scc-backend-app-cmap
data:
  KUBE_CACHING_ENABLED: "true"
  KUBE_MEDIA_DATA_DIRECTORY: /var/data
  KUBE_MONGO_CONNECTION_URI: mongodb://scc-backend-mongodb:27017
  KUBE_MONGO_DATABASE_NAME: scc-backend
  KUBE_MONGO_AUCTION_COLLECTION: auctions
  KUBE_MONGO_BID_COLLECTION: bids
  KUBE_MONGO_QUESTION_COLLECTION: questions
  KUBE_MONGO_USER_COLLECTION: users
  KUBE_REDIS_URL: scc-backend-redis
  KUBE_REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-backend-app
spec:
  selector:
    matchLabels:
      app: scc-backend-app
  template:
    metadata:
      labels:
        app: scc-backend-app
    spec:
      containers:
        - name: scc-backend-app
          image: localhost:5000/scc-backend-app
          resources:
            limits:
              memory: "2Gi"
              cpu: "4"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: scc-backend-app-cmap
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-app
spec:
  type: LoadBalancer
  selector:
    app: scc-backend-app
  ports:
    - port: 8080
