---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-backend-mongodb
spec:
  selector:
    matchLabels:
      app: scc-backend-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scc-backend-mongodb
    spec:
      containers:
        - name: scc-backend-mongodb
          image: docker.io/mongo:5.0.14
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-mongodb
spec:
  selector:
    app: scc-backend-mongodb
  ports:
    - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend-mongodb-ld
spec:
  type: LoadBalancer
  selector:
    app: scc-backend-mongodb
  ports:
    - port: 27017
