---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scc-backend-cmap
data:
  KUBE_CACHING_ENABLED: "true"
  KUBE_MEDIA_DATA_DIRECTORY: /var/data
  KUBE_MONGO_CONNECTION_URI: mongodb://scc-mongodb:27017
  KUBE_MONGO_DATABASE_NAME: scc-backend
  KUBE_MONGO_AUCTION_COLLECTION: auctions
  KUBE_MONGO_BID_COLLECTION: bids
  KUBE_MONGO_QUESTION_COLLECTION: questions
  KUBE_MONGO_USER_COLLECTION: users
  KUBE_REDIS_URL: scc-redis
  KUBE_REDIS_PORT: "6379"
  KUBE_RABBITMQ_HOST: scc-rabbitmq
  KUBE_OTLP_ENABLED: "true"
  KUBE_RABBITMQ_PORT: "5672"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-backend
spec:
  selector:
    matchLabels:
      app: scc-backend
  template:
    metadata:
      labels:
        app: scc-backend
    spec:
      containers:
        - name: scc-backend
          image: git.d464.sh/diogo464/scc-backend
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: scc-backend-cmap
---
apiVersion: v1
kind: Service
metadata:
  name: scc-backend
spec:
  type: LoadBalancer
  selector:
    app: scc-backend
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-worker-user-scrub
spec:
  selector:
    matchLabels:
      app: scc-worker-user-scrub
  template:
    metadata:
      labels:
        app: scc-worker-user-scrub
    spec:
      containers:
        - name: scc-worker-user-scrub
          image: git.d464.sh/diogo464/scc-worker
          args: [scc.worker.UserScrub]
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
          envFrom:
            - configMapRef:
                name: scc-backend-cmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-worker-auction-close
spec:
  selector:
    matchLabels:
      app: scc-worker-auction-close
  template:
    metadata:
      labels:
        app: scc-worker-auction-close
    spec:
      containers:
        - name: scc-worker-auction-close
          image: git.d464.sh/diogo464/scc-worker
          args: [scc.worker.AuctionClose]
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
          envFrom:
            - configMapRef:
                name: scc-backend-cmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-worker-auction-popularity
spec:
  selector:
    matchLabels:
      app: scc-worker-auction-popularity
  template:
    metadata:
      labels:
        app: scc-worker-auction-popularity
    spec:
      containers:
        - name: scc-worker-auction-popularity
          image: git.d464.sh/diogo464/scc-worker
          args: [scc.worker.AuctionPopularity]
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          envFrom:
            - configMapRef:
                name: scc-backend-cmap
